# Generated by Django 3.0.5 on 2020-04-20 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='System')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'System',
                'verbose_name_plural': 'System',
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveIntegerField(choices=[(10, 'Comfort Classic'), (11, 'Comfort Top (only icw Comfort Classic)'), (12, 'Comfort Top Plus (only icw Comfort Top)'), (20, 'Driver Operation Classic'), (21, 'Driver Operation Top (only icw Operation Classic)'), (30, 'Efficiency Classic'), (40, 'Express Classic'), (41, 'Express Top (only icw Express Classic)'), (1, 'Safety Top (only icw Express Top)'), (2, 'Mountain'), (3, 'Light Weight'), (4, 'Road Star'), (5, 'Summer Package (only icw Comfort Top)'), (6, 'Winter Package (only icw Comfort Classic)')], verbose_name='Packages')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Packages',
                'verbose_name_plural': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='DriveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveIntegerField(choices=[(1, '6X4'), (2, '6X2'), (3, '4X2')], verbose_name='Drive Type')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Drive Type',
                'verbose_name_plural': 'Drive Type',
            },
        ),
        migrations.CreateModel(
            name='CodesH6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Code')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('comments', models.CharField(max_length=300, verbose_name='Comments')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Active'), (0, 'Deleted')], verbose_name='Status')),
                ('restriction_with', models.CharField(max_length=500, verbose_name='With')),
                ('restriction_not_with', models.CharField(max_length=500, verbose_name='Not With')),
                ('brand', models.PositiveIntegerField(choices=[(1, 'H6A'), (2, 'H6B'), (3, 'H6')], verbose_name='')),
                ('personal_comments', models.CharField(max_length=500, verbose_name='Personal Comments')),
                ('knowledge', models.CharField(max_length=500, verbose_name='Knowledge')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('drive_type', models.ManyToManyField(to='codes.DriveType', verbose_name='Drive Type')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('package', models.ManyToManyField(to='codes.Packages', verbose_name='Package')),
                ('system', models.ManyToManyField(to='codes.System', verbose_name='System')),
            ],
            options={
                'verbose_name': 'H6 Codes',
                'verbose_name_plural': 'H6 Codes',
            },
        ),
    ]
